development:
  mail_password: PASSWORD
  hostname: localhost:3000

production:
  mail_password: PASSWORD
  hostname: achievements.heroku.com

test:  
  mail_password: PASSWORD
  hostname: localhost
  